-- Table Definition ----------------------------------------------

CREATE TABLE applicants (
    email text PRIMARY KEY,
    full_name text NOT NULL,
    password text NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX applicants_pkey ON applicants(email text_ops);


-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE applications (
    application_id text PRIMARY KEY,
    applicant_email text REFERENCES applicants(email) ON DELETE RESTRICT ON UPDATE CASCADE,
    exam_id text REFERENCES exams(exam_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    status text NOT NULL,
    questions_total integer,
    questions_correct integer,
    questions_wrong integer,
    questions_unanswered integer,
    eval_pct numeric(5,2)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX applications_pkey ON applications(application_id text_ops);


-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE choices (
    choice_id text PRIMARY KEY,
    choice_text text NOT NULL,
    question_id text REFERENCES questions(question_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX choices_pkey ON choices(choice_id text_ops);

-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE examiners (
    username text PRIMARY KEY,
    email text,
    first_name text NOT NULL,
    last_name text,
    password text NOT NULL,
    org_handle text NOT NULL REFERENCES organizations(handle) ON DELETE SET NULL ON UPDATE CASCADE,
    photo_url text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX examiners_pkey ON examiners(username text_ops);

-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE exams (
    exam_id text PRIMARY KEY,
    exam_name text NOT NULL,
    exam_description text,
    exam_owner text NOT NULL REFERENCES examiners(username) ON DELETE SET NULL ON UPDATE CASCADE,
    exam_fee money DEFAULT 0.00,
    exam_pass_score integer DEFAULT 70,
    exam_status text DEFAULT 'enabled'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX exams_pkey ON exams(exam_id text_ops);

-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE organizations (
    handle text PRIMARY KEY,
    key text NOT NULL,
    name text NOT NULL,
    logo_url text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX organizations_pkey ON organizations(handle text_ops);


-- DDL generated by Postico 1.5.13
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE questions (
    question_id text PRIMARY KEY,
    question_type text NOT NULL,
    question_text text NOT NULL,
    question_seq integer NOT NULL,
    valid_answer_id text NOT NULL,
    exam_id text REFERENCES exams(exam_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX questions_pkey ON questions(question_id text_ops);
